"""Run the pipeline on a timer via Windows Task Scheduler.

Generates a small .cmd wrapper (so the task runs in the project directory with
the right interpreter) and registers a daily task pointing at it.

`schtasks` writes to your user's task store. Nothing here runs automatically as
a side effect of anything else -- you invoke `schedule install` deliberately,
and `schedule remove` undoes it completely.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from .db import PROJECT_ROOT

TASK_NAME = "JobSearchPipeline"
WRAPPER_NAME = "run_pipeline.cmd"


@dataclass
class ScheduleResult:
    ok: bool
    detail: str
    command: str = ""


def wrapper_path() -> Path:
    return PROJECT_ROOT / WRAPPER_NAME


def write_wrapper(*, db_path: str | None = None, log: bool = True) -> Path:
    """A .cmd that activates the right interpreter and runs one pass."""
    python = Path(sys.executable)
    log_line = (
        f'>> "{PROJECT_ROOT / "output" / "pipeline.log"}" 2>&1' if log else ""
    )
    db_flag = f' --db "{db_path}"' if db_path else ""
    script = (
        "@echo off\r\n"
        "REM Generated by: python -m jobsearch schedule install\r\n"
        "REM Delete this file and run `schedule remove` to undo.\r\n"
        f'cd /d "{PROJECT_ROOT}"\r\n'
        f'if not exist "{PROJECT_ROOT / "output"}" mkdir "{PROJECT_ROOT / "output"}"\r\n'
        f'echo [%date% %time%] starting run {log_line}\r\n'
        f'"{python}" -m jobsearch run{db_flag} {log_line}\r\n'
    )
    path = wrapper_path()
    path.write_text(script, encoding="utf-8")
    return path


def _schtasks_available() -> bool:
    return sys.platform == "win32" and shutil.which("schtasks") is not None


def install(*, at: str = "08:00", db_path: str | None = None) -> ScheduleResult:
    if not _schtasks_available():
        return ScheduleResult(
            False,
            "schtasks is only available on Windows. On Linux/macOS use cron:\n"
            f"  0 8 * * *  cd {PROJECT_ROOT} && {sys.executable} -m jobsearch run",
        )
    try:
        hour, _, minute = at.partition(":")
        normalized = f"{int(hour):02d}:{int(minute or 0):02d}"
    except ValueError:
        return ScheduleResult(False, f"'{at}' is not a HH:MM time")

    wrapper = write_wrapper(db_path=db_path)
    command = (
        f'schtasks /Create /TN "{TASK_NAME}" /TR "\\"{wrapper}\\"" '
        f"/SC DAILY /ST {normalized} /F"
    )
    try:
        completed = subprocess.run(
            [
                "schtasks", "/Create",
                "/TN", TASK_NAME,
                "/TR", f'"{wrapper}"',
                "/SC", "DAILY",
                "/ST", normalized,
                "/F",
            ],
            capture_output=True,
            text=True,
        )
    except OSError as exc:
        return ScheduleResult(False, f"could not run schtasks: {exc}", command)

    if completed.returncode != 0:
        return ScheduleResult(
            False,
            (completed.stderr or completed.stdout or "schtasks failed").strip(),
            command,
        )
    return ScheduleResult(
        True, f"'{TASK_NAME}' will run daily at {normalized} via {wrapper}", command
    )


def remove() -> ScheduleResult:
    if not _schtasks_available():
        return ScheduleResult(False, "schtasks is only available on Windows.")
    completed = subprocess.run(
        ["schtasks", "/Delete", "/TN", TASK_NAME, "/F"], capture_output=True, text=True
    )
    if completed.returncode != 0:
        return ScheduleResult(
            False, (completed.stderr or completed.stdout or "not found").strip()
        )
    wrapper = wrapper_path()
    if wrapper.is_file():
        wrapper.unlink()
    return ScheduleResult(True, f"removed '{TASK_NAME}' and its wrapper script")


def status() -> ScheduleResult:
    if not _schtasks_available():
        return ScheduleResult(False, "schtasks is only available on Windows.")
    completed = subprocess.run(
        ["schtasks", "/Query", "/TN", TASK_NAME, "/FO", "LIST"],
        capture_output=True,
        text=True,
    )
    if completed.returncode != 0:
        return ScheduleResult(False, f"'{TASK_NAME}' is not registered")
    return ScheduleResult(True, (completed.stdout or "").strip())
